update files of remote gt to version v1.5.2 via gt

diff --git a/.github/workflows/gt-update.yml b/.github/workflows/gt-update.yml
--- a/.github/workflows/gt-update.yml
+++ b/.github/workflows/gt-update.yml
@@ -5,19 +5,29 @@
 #  \__/\__/\_, /\___/_//_/\_,_/_/         It is licensed under European Union Public License v. 1.2
 #         /___/                           Please report bugs and contribute back your improvements
 #
-#                                         Version: v1.4.4
+#                                         Version: v1.5.2
 ###################################
 name: "gt update"
+
+#gt-placeholder-trigger-start
 on:
   schedule:
     - cron: '0 4 * * MON'
   workflow_dispatch:
+#gt-placeholder-trigger-end
+
+permissions:
+  contents: read
 
 jobs:
   determine_remotes:
     name: Determine Remotes
     runs-on: ubuntu-latest
+
+    # gt-placeholder-owner-start
     if: github.repository_owner == 'tegonal'
+    # gt-placeholder-owner-end
+
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
@@ -32,21 +42,28 @@ jobs:
         run: |
           set -e
           # see install.doc.sh in https://github.com/tegonal/gt, MODIFY THERE NOT HERE (please report bugs)
-          currentDir=$(pwd) && \
-          tmpDir=$(mktemp -d -t gt-download-install-XXXXXXXXXX) && cd "$tmpDir" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc.sig" && \
-          gpg --verify ./signing-key.public.asc.sig ./signing-key.public.asc && \
-          echo "public key trusted" && \
-          mkdir ./gpg && \
-          gpg --homedir ./gpg --import ./signing-key.public.asc && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh.sig" && \
-          gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh && \
-          chmod +x ./install.sh && \
-          echo "verification successful" || (printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!\n"; exit 1) && \
-          ./install.sh && result=true || (echo >&2 "installation failed"; exit 1) && \
-          false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
+          #!/usr/bin/env bash
+          currentDir=$(pwd) &&
+          	tmpDir=$(mktemp -d -t gt-download-install-XXXXXXXXXX) && cd "$tmpDir" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc.sig" &&
+          	gpg --verify ./signing-key.public.asc.sig ./signing-key.public.asc &&
+          	echo "public key trusted" &&
+          	mkdir ./gpg &&
+          	gpg --homedir ./gpg --import ./signing-key.public.asc &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh.sig" &&
+          	gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh &&
+          	chmod +x ./install.sh &&
+          	echo "verification successful" ||
+          	{
+          		printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!\n"
+          		exit 1
+          	} && ./install.sh && result=true ||
+          	{
+          		echo >&2 "installation failed"
+          		exit 1
+          	} && false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
           # end install.doc.sh
       - uses: actions/checkout@v5
       - id: set-matrix
@@ -71,21 +88,28 @@ jobs:
         run: |
           set -e
           # see install.doc.sh in https://github.com/tegonal/gt, MODIFY THERE NOT HERE (please report bugs)
-          currentDir=$(pwd) && \
-          tmpDir=$(mktemp -d -t gt-download-install-XXXXXXXXXX) && cd "$tmpDir" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc.sig" && \
-          gpg --verify ./signing-key.public.asc.sig ./signing-key.public.asc && \
-          echo "public key trusted" && \
-          mkdir ./gpg && \
-          gpg --homedir ./gpg --import ./signing-key.public.asc && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh" && \
-          wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh.sig" && \
-          gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh && \
-          chmod +x ./install.sh && \
-          echo "verification successful" || (printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!\n"; exit 1) && \
-          ./install.sh && result=true || (echo >&2 "installation failed"; exit 1) && \
-          false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
+          #!/usr/bin/env bash
+          currentDir=$(pwd) &&
+          	tmpDir=$(mktemp -d -t gt-download-install-XXXXXXXXXX) && cd "$tmpDir" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/main/.gt/signing-key.public.asc.sig" &&
+          	gpg --verify ./signing-key.public.asc.sig ./signing-key.public.asc &&
+          	echo "public key trusted" &&
+          	mkdir ./gpg &&
+          	gpg --homedir ./gpg --import ./signing-key.public.asc &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh" &&
+          	wget "https://raw.githubusercontent.com/tegonal/gt/v1.4.4/install.sh.sig" &&
+          	gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh &&
+          	chmod +x ./install.sh &&
+          	echo "verification successful" ||
+          	{
+          		printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!\n"
+          		exit 1
+          	} && ./install.sh && result=true ||
+          	{
+          		echo >&2 "installation failed"
+          		exit 1
+          	} && false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
           # end install.doc.sh
       - uses: actions/checkout@v5
       - name: reset gpg keys
